server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/everdeliver
    username: everdeliver
    password: everdeliver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  endpoints:
    web:
      exposure:
        include: health

everdeliver:
  delivery:
    block-private-hosts: false
