server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/everdeliver
    username: everdeliver
    password: everdeliver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: false
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: everdeliver-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.everdeliver.common"
  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
